import {MenuItem} from '../models/menu.model';

// menu items for vertcal and detached layout
const MENU_ITEMS: MenuItem[] = [
    { key: 'dashboard', label: 'Tổng Quan', isTitle: true },
    {
        key: 'dashboard',
        label: 'Thống kê',
        isTitle: false,
        icon: 'home',
        collapsed: true,
        // badge: { variant: 'danger', text: '02' },
        children: [
            {
                key: 'ds-ecommerce',
                label: 'Tổng Quan Dự Án',
                link: '/dashboard/tong-quan-du-an',
                parentKey: 'dashboard',
            },
            // {
            //     key: 'ds-analytics',
            //     label: 'Analytics',
            //     link: '/dashboard/analytics',
            //     parentKey: 'dashboard',
            // }
        ],
    },

    {key: 'noi-bo', label: 'Nội bộ ISofH', isTitle: true},
    {
        key: 'noi-bo',
        label: 'Máy chủ nội bộ',
        isTitle: false,
        icon: 'home',
        badge: { variant: 'primary', text: 'nội bộ' },
        collapsed: true,
        children: [
            {
                key: 'sys-team',
                label: 'Thông tin server ISofH',
                link: '/noi-bo/systems-team',
                parentKey: 'noi-bo',
            },
            {
                key: 'jira-company',
                label: 'Database Jira',
                link: '/noi-bo/jira-company',
                parentKey: 'noi-bo',
            },
            {
                key: 'jira-confluence',
                label: 'Database Confluence',
                link: '/noi-bo/jira-confluence',
                parentKey: 'noi-bo',
            },
        ],
    },
    {key: 'benh-vien', label: 'Danh sách bệnh viện', isTitle: true},
    {
        key: 'bv-pk40',
        label: 'Phòng Khám 4.0  ',
        isTitle: false,
        badge: { variant: 'success', text: 'mới' },
        icon: 'globe',
        collapsed: true,
        children: [
            {
                key: 'bv-pk40-info',
                label: 'Thông tin server UBKH',
                link: 'benh-vien/bv-pk40/info',
                parentKey: 'bv-pk40',
            },
            {
                key: 'bv-pk40-database',
                label: 'Database UBKH',
                link: 'benh-vien/bv-pk40',
                parentKey: 'bv-pk40',
            },
        ],
    },
    {
        key: 'bv-ubkh',
        label: 'UB Khánh Hòa  ',
        isTitle: false,
        badge: { variant: 'success', text: 'mới' },
        icon: 'globe',
        collapsed: true,
        children: [
            {
                key: 'bv-ubkh-info',
                label: 'Thông tin server UBKH',
                link: 'benh-vien/bv-ubkh/info',
                parentKey: 'bv-ubkh',
            },
            {
                key: 'bv-ubkh-database',
                label: 'Database UBKH',
                link: 'benh-vien/bv-ubkh',
                parentKey: 'bv-ubkh',
            },
        ],
    },
    {
        key: 'bv-ndtp',
        label: 'Viện NĐTP  ',
        isTitle: false,
        icon: 'globe',
        badge: { variant: 'success', text: 'mới' },
        collapsed: true,
        children: [
            {
                key: 'bv-ndtp-info',
                label: 'Thông tin server NĐTP',
                link: 'benh-vien/bv-ndtp/info',
                parentKey: 'bv-ndtp',
            },
            {
                key: 'bv-ndtp-database',
                label: 'Database Prod NĐTP',
                link: 'benh-vien/bv-ndtp',
                parentKey: 'bv-ndtp',
            },
        ],
    },
    {
        key: 'bv-e',
        label: 'Bệnh viện E',
        isTitle: false,
        icon: 'globe',
        collapsed: true,
        children: [
            {
                key: 'bv-e-info',
                label: 'Thông tin server Viện E',
                link: 'benh-vien/bv-e/info',
                parentKey: 'bv-e',
            },
            {
                key: 'bv-e-database',
                label: 'Database Prod Viện E',
                link: 'benh-vien/bv-e',
                parentKey: 'bv-e',
            },
        ],
    },
    {
        key: 'bv-mediplus',
        label: 'MediPlus  ',
        isTitle: false,
        icon: 'globe',
        collapsed: true,
        children: [
            {
                key: 'bv-mediplus-info',
                label: 'Thông tin server MediPlus',
                link: 'benh-vien/bv-mediplus/info',
                parentKey: 'bv-mediplus',
            },
            {
                key: 'bv-mediplus-database',
                label: 'Database Prod Medi+',
                link: 'benh-vien/bv-mediplus',
                parentKey: 'bv-mediplus',
            },
        ],
    },
    {
        key: 'bv-xanhfon',
        label: 'BV Saint Paul  ',
        isTitle: false,
        icon: 'globe',
        collapsed: true,
        children: [
            {
                key: 'bv-xanhfon-info',
                label: 'Thông tin server Xanh Phôn',
                link: 'benh-vien/bv-xanhfon/info',
                parentKey: 'bv-xanhfon',
            },
            {
                key: 'bv-xanhfon-database',
                label: 'Database Xanh Phôn',
                link: 'benh-vien/bv-xanhfon',
                parentKey: 'bv-xanhfon',
            },
        ],
    },
    {
        key: 'bv-daihoc-y',
        label: 'Viện ĐH Y  ',
        isTitle: false,
        icon: 'globe',
        collapsed: true,
        children: [
            {
                key: 'bv-daihoc-info',
                label: 'Thông tin server DHY',
                link: 'benh-vien/bv-daihoc-y/info',
                parentKey: 'bv-daihoc-y',
            },
            {
                key: 'bv-daihoc-y-database',
                label: 'Database DHY',
                link: 'benh-vien/bv-daihoc-y',
                parentKey: 'bv-daihoc-y',
            },
        ],
    },
    {
        key: 'bv-bachmai',
        label: 'Bạch mai  ',
        isTitle: false,
        icon: 'globe',
        collapsed: true,
        children: [
            {
                key: 'bv-bachmai-info',
                label: 'Thông tin server Bạch Mai',
                link: 'benh-vien/bv-bachmai/info',
                parentKey: 'bv-bachmai',
            },
            {
                key: 'bv-bachmai-database',
                label: 'Database Bạch Mai',
                link: 'benh-vien/bv-bachmai',
                parentKey: 'bv-bachmai',
            },
        ],
    },
    {
        key: 'bv-allen',
        label: 'Doctor Allen  ',
        isTitle: false,
        icon: 'globe',
        collapsed: true,
        children: [
            {
                key: 'bv-allen-info',
                label: 'Thông tin server Dr.Allen',
                link: 'benh-vien/bv-allen/info',
                parentKey: 'bv-allen',
            },
            {
                key: 'bv-allen',
                label: 'Database Dr.Allen',
                link: 'benh-vien/bv-allen',
                parentKey: 'benh-vien',
            },
        ],
    },
    {
        key: 'bv-tttm',
        label: 'TTTM Viện E  ',
        isTitle: false,
        icon: 'globe',
        collapsed: true,
        children: [
            {
                key: 'bv-tttm-info',
                label: 'Thông tin server TTTM',
                link: 'benh-vien/bv-tttm/info',
                parentKey: 'bv-tttm',
            },
            {
                key: 'bv-tttm-database',
                label: 'Database TTTM',
                link: 'benh-vien/bv-tttm',
                parentKey: 'bv-tttm',
            },
        ],
    },
    // {
    //     key: 'bv-dt',
    //     label: 'Đồng Tâm (bỏ)',
    //     isTitle: false,
    //     icon: 'globe',
    //     collapsed: true,
    //     children: [
    //         {
    //             key: 'bv-dt-info',
    //             label: 'Thông tin server Đồng Tâm',
    //             link: 'benh-vien/bv-dt/info',
    //             parentKey: 'bv-dt',
    //         },
    //         {
    //             key: 'bv-dt-database',
    //             label: 'Database BVĐT',
    //             link: 'benh-vien/bv-dt',
    //             parentKey: 'bv-dt',
    //         },
    //     ],
    // },
    {
        key: 'bv-ytcc',
        label: 'YTCC ',
        isTitle: false,
        icon: 'globe',
        collapsed: true,
        children: [
            {
                key: 'bv-ytcc-info',
                label: 'Thông tin server YTCC',
                link: 'benh-vien/bv-ytcc/info',
                parentKey: 'bv-ytcc',
            },
            {
                key: 'bv-ytcc-database',
                label: 'Database YTCC',
                link: 'benh-vien/bv-ytcc',
                parentKey: 'bv-ytcc',
            },
        ],
    },
    {
        key: 'bv-dkth',
        label: 'ĐK Thanh Hóa',
        isTitle: false,
        icon: 'globe',
        collapsed: true,
        children: [
            {
                key: 'bv-dkth-info',
                label: 'Thông tin server ĐKTH',
                link: 'benh-vien/bv-dkth/info',
                parentKey: 'bv-dkth',
            },
            {
                key: 'bv-dkth-db-prod',
                label: 'Database Prod',
                link: 'benh-vien/bv-dkth/db-prod',
                parentKey: 'bv-dkth',
            },
            {
                key: 'bv-dkth-db-emr',
                label: 'Database EMR',
                link: 'benh-vien/bv-dkth/db-emr',
                parentKey: 'bv-dkth',
            },
        ],
    },
    {
        key: 'bv-psta',
        label: 'PS Thiện An  ',
        isTitle: false,
        icon: 'globe',
        collapsed: true,
        children: [
            {
                key: 'bv-psta-info',
                label: 'Thông tin server PSTA',
                link: 'benh-vien/bv-psta/info',
                parentKey: 'bv-psta',
            },
            {
                key: 'bv-psta-database',
                label: 'Database PSTA',
                link: 'benh-vien/bv-psta',
                parentKey: 'bv-psta',
            },
        ],
    },
    {
        key: 'bv-phoi',
        label: 'BV Phổi  ',
        isTitle: false,
        icon: 'globe',
        collapsed: true,
        children: [
            {
                key: 'bv-phoi-info',
                label: 'Thông tin server Phổi',
                link: 'benh-vien/bv-phoi/info',
                parentKey: 'bv-phoi',
            },
            {
                key: 'bv-phoi-database',
                label: 'Database Phổi',
                link: 'benh-vien/bv-phoi',
                parentKey: 'bv-phoi',
            },
        ],
    },
    {
        key: 'bv-vietmy',
        label: 'BV Việt Mỹ  ',
        isTitle: false,
        icon: 'globe',
        collapsed: true,
        children: [
            {
                key: 'bv-vietmy-info',
                label: 'Thông tin server Việt Mỹ',
                link: 'benh-vien/bv-vietmy/info',
                parentKey: 'bv-vietmy',
            },
            {
                key: 'bv-vietmy-database',
                label: 'Database Việt Mỹ',
                link: 'benh-vien/bv-vietmy',
                parentKey: 'bv-vietmy',
            },
        ],
    },
    {
        key: 'bv-qy110',
        label: 'Viện QY 110  ',
        isTitle: false,
        icon: 'globe',
        collapsed: true,
        children: [
            {
                key: 'bv-qy110-info',
                label: 'Thông tin server QY110',
                link: 'benh-vien/bv-qy110/info',
                parentKey: 'bv-qy110',
            },
            {
                key: 'bv-qy110-database',
                label: 'Database QY110',
                link: 'benh-vien/bv-qy110',
                parentKey: 'bv-qy110',
            },
        ],
    },
    // {
    //     key: 'bv-vietlife',
    //     label: 'Bệnh viện VietLife',
    //     isTitle: false,
    //     icon: 'globe',
    //     collapsed: true,
    //     children: [
    //         {
    //             key: 'bv-vietlife-info',
    //             label: 'Thông tin server VietLife',
    //             link: 'benh-vien/bv-vietlife/info',
    //             parentKey: 'bv-vietlife',
    //         },
    //         {
    //             key: 'bv-qy10-database',
    //             label: 'Database VietLife',
    //             link: 'benh-vien/bv-vietlife',
    //             parentKey: 'bv-vietlife',
    //         },
    //     ],
    // },
    {
        key: 'bv-vietnhat',
        label: 'BV Việt Nhật  ',
        isTitle: false,
        icon: 'globe',
        collapsed: true,
        children: [
            {
                key: 'bv-vietnhat-info',
                label: 'Thông tin server Việt Nhật',
                link: 'benh-vien/bv-vietnhat/info',
                parentKey: 'bv-vietnhat',
            },
            {
                key: 'bv-vietnhat-database',
                label: 'Database Việt Nhật',
                link: 'benh-vien/bv-vietnhat',
                parentKey: 'bv-vietnhat',
            },
        ],
    },
    {
        key: 'bv-ctm',
        label: 'Chân Trời Mới',
        isTitle: false,
        icon: 'globe',
        collapsed: true,
        badge: { variant: 'danger', text: 'non Pass' },
        children: [
            {
                key: 'bv-ctm-info',
                label: 'Thông tin server CTM',
                link: 'benh-vien/bv-ctm/info',
                parentKey: 'bv-ctm',
            },
            {
                key: 'bv-ctm-database',
                label: 'Database CTM',
                link: 'benh-vien/bv-ctm',
                parentKey: 'bv-ctm',
            },
        ],
    },
    {
        key: 'bv-myrehab',
        label: 'MyRehab',
        isTitle: false,
        icon: 'globe',
        badge: { variant: 'danger', text: 'jump' },
        collapsed: true,
        children: [
            {
                key: 'bv-myrehab-info',
                label: 'Thông tin server MyRehab',
                link: 'benh-vien/bv-myrehab/info',
                parentKey: 'bv-myrehab',
            },
            {
                key: 'bv-myrehab-database',
                label: 'Database MyRehab',
                link: 'benh-vien/bv-myrehab',
                parentKey: 'bv-myrehab',
            },
        ],
    },
    {
        key: 'bv-thaihoa',
        label: 'Thái Hòa',
        isTitle: false,
        badge: { variant: 'danger', text: 'no VPN' },
        icon: 'globe',
        collapsed: true,
        children: [
            {
                key: 'bv-thaihoa-info',
                label: 'Thông tin server Thái Hòa',
                link: 'benh-vien/bv-thaihoa/info',
                parentKey: 'bv-thaihoa',
            },
            {
                key: 'bv-thaihoa-database',
                label: 'Database Thái Hòa',
                link: 'benh-vien/bv-thaihoa',
                parentKey: 'bv-thaihoa',
            },
        ],
    },
    // {
    //     key: 'bv-y',
    //     label: 'Bệnh viện Đại học Y',
    //     isTitle: false,
    //     icon: 'globe',
    //     collapsed: true,
    //     children: [
    //         // {
    //         //     key: 'benh-vien-y',
    //         //     label: 'Inbox',
    //         //     link: '/apps/eglobe/inbox',
    //         //     parentKey: 'benh-vien',
    //         // },
    //     ],
    // },
    // {
    //     key: 'bv-dkth',
    //     label: 'BV ĐK Thanh Hóa',
    //     isTitle: false,
    //     icon: 'globe',
    //     collapsed: true,
    //     children: [],
    // },
    // {
    //     key: 'bv-phoi',
    //     label: 'BV Phổi TW',
    //     isTitle: false,
    //     icon: 'globe',
    //     collapsed: true,
    //     children: [],
    // },
    // {
    //     key: 'bv-psta',
    //     label: 'BV Phụ sản TA',
    //     isTitle: false,
    //     icon: 'globe',
    //     collapsed: true,
    //     children: [],
    // },
    // {
    //     key: 'bv-qyq110',
    //     label: 'BV Quân Y 110',
    //     isTitle: false,
    //     icon: 'globe',
    //     collapsed: true,
    //     children: [],
    // },
    // {
    //     key: 'bv-xanhpon',
    //     label: 'BV Xanh Phôn',
    //     isTitle: false,
    //     icon: 'globe',
    //     collapsed: true,
    //     children: [],
    // },
    // {
    //     key: 'bv-tttm',
    //     label: 'TT Tim Mạch (viện E)',
    //     isTitle: false,
    //     icon: 'globe',
    //     collapsed: true,
    //     children: [],
    // },
    // {
    //     key: 'bv-medi',
    //     label: 'Bệnh viện Mediplus',
    //     isTitle: false,
    //     icon: 'globe',
    //     collapsed: true,
    //     children: [],
    // },
    // {
    //     key: 'bv-ykhn',
    //     label: 'BV Y Khoa HN',
    //     isTitle: false,
    //     icon: 'globe',
    //     collapsed: true,
    //     children: [],
    // },
    // {
    //     key: 'bv-bm',
    //     label: 'BV Bạch Mai',
    //     isTitle: false,
    //     icon: 'globe',
    //     collapsed: true,
    //     children: [],
    // },
    // {
    //     key: 'bv-ytcc',
    //     label: 'Y Tế Công Cộng',
    //     isTitle: false,
    //     icon: 'globe',
    //     collapsed: true,
    //     children: [],
    // },
    // {
    //     key: 'bv-rehab',
    //     label: 'Y Tế My Rehab',
    //     isTitle: false,
    //     icon: 'globe',
    //     collapsed: true,
    //     children: [],
    // },
    // {
    //     key: 'bv-vietmy',
    //     label: 'BV Việt Mỹ',
    //     isTitle: false,
    //     icon: 'globe',
    //     collapsed: true,
    //     children: [],
    // },
    // {
    //     key: 'bv-dt',
    //     label: 'BV Đồng Tâm',
    //     isTitle: false,
    //     icon: 'globe',
    //     collapsed: true,
    //     children: [],
    // },
    // {
    //     key: 'bv-allen',
    //     label: 'Y Tế Dr.Allen',
    //     isTitle: false,
    //     icon: 'globe',
    //     collapsed: true,
    //     children: [],
    // },
    // {
    //     key: 'bv-vnhsc',
    //     label: 'Y Tế VNHSC',
    //     isTitle: false,
    //     icon: 'globe',
    //     collapsed: true,
    //     children: [],
    // },
    // {
    //     key: 'bv-ytcc',
    //     label: 'Y Tế Công Cộng',
    //     isTitle: false,
    //     icon: 'globe',
    //     collapsed: true,
    //     children: [],
    // },
    // { key: 'dashboard', label: 'Nội bộ ISofH', isTitle: true },
    // {
    //     key: 'dashboard',
    //     label: 'Máy chủ nội bộ',
    //     isTitle: false,
    //     icon: 'home',
    //     collapsed: true,
    //     // badge: { variant: 'success', text: '02' },
    //     children: [
    //         {
    //             key: 'ds-ecommerce',
    //             label: 'Database Jira',
    //             link: '/dashboard/ecommerce',
    //             parentKey: 'dashboard',
    //         },
    //         {
    //             key: 'ds-analytics',
    //             label: 'Database Confluence',
    //             link: '/dashboard/analytics',
    //             parentKey: 'dashboard',
    //         }
    //     ],
    // },

    // { key: 'apps', label: 'Danh sách bệnh viện', isTitle: true },
    // {
    //     key: 'apps-calendar',
    //     label: 'Calendar',
    //     isTitle: false,
    //     icon: 'calendar',
    //     link: '/apps/calendar',
    // },
    // {
    //     key: 'apps-chat',
    //     label: 'Chat',
    //     isTitle: false,
    //     icon: 'message-square',
    //     link: '/apps/chat',
    // },
    // {
    //     key: 'apps-eglobe',
    //     label: 'Eglobe',
    //     isTitle: false,
    //     icon: 'globe',
    //     collapsed: true,
    //     children: [
    //         {
    //             key: 'eglobe-inbox',
    //             label: 'Inbox',
    //             link: '/apps/eglobe/inbox',
    //             parentKey: 'apps-eglobe',
    //         },
    //         {
    //             key: 'eglobe-read-eglobe',
    //             label: 'Read Eglobe',
    //             link: '/apps/eglobe/details',
    //             parentKey: 'apps-eglobe',
    //         },
    //         {
    //             key: 'eglobe-compose-eglobe',
    //             label: 'Compose Eglobe',
    //             link: '/apps/eglobe/compose',
    //             parentKey: 'apps-eglobe',
    //         },
    //     ],
    // },
    // {
    //     key: 'apps-projects',
    //     label: 'Projects',
    //     isTitle: false,
    //     icon: 'briefcase',
    //     collapsed: true,
    //     children: [
    //         { key: 'project-list', label: 'List', link: '/apps/projects/list', parentKey: 'apps-projects' },
    //         {
    //             key: 'project-details',
    //             label: 'Detail',
    //             link: '/apps/projects/details',
    //             parentKey: 'apps-projects',
    //         }
    //     ],
    // },
    // {
    //     key: 'apps-tasks',
    //     label: 'Tasks',
    //     isTitle: false,
    //     icon: 'clipboard',
    //     collapsed: true,
    //     children: [
    //         { key: 'task-list', label: 'List', link: '/apps/tasks/list', parentKey: 'apps-tasks' },
    //         { key: 'task-kanban', label: 'Kanban Board', link: '/apps/tasks/kanban', parentKey: 'apps-tasks' },
    //     ],
    // },
    // {
    //     key: 'apps-file-manager',
    //     label: 'File Manager',
    //     isTitle: false,
    //     icon: 'file-plus',
    //     link: '/apps/file-manager',
    // },
    // { key: 'custom', label: 'Custom', isTitle: true },
    // {
    //     key: 'extra-pages',
    //     label: 'Pages',
    //     isTitle: false,
    //     icon: 'file-text',
    //     collapsed: true,
    //     children: [
    //         { key: 'page-starter', label: 'Starter', link: '/pages/starter', parentKey: 'extra-pages' },
    //         { key: 'page-profile', label: 'Profile', link: '/pages/profile', parentKey: 'extra-pages' },
    //         { key: 'page-activity', label: 'Activity', link: '/pages/activity', parentKey: 'extra-pages' },
    //         { key: 'page-invoice', label: 'Invoice', link: '/pages/invoice', parentKey: 'extra-pages' },
    //         { key: 'page-pricing', label: 'Pricing', link: '/pages/pricing', parentKey: 'extra-pages' },
    //         {
    //             key: 'page-maintenance',
    //             label: 'Maintenance',
    //             link: '/maintenance',
    //             parentKey: 'extra-pages',
    //         },
    //         { key: 'page-error-404', label: 'Error - 404', link: '/error-404', parentKey: 'extra-pages' },
    //         { key: 'page-error-500', label: 'Error - 500', link: '/error-500', parentKey: 'extra-pages' },
    //     ],
    // },
    // { key: 'components', label: 'Components', isTitle: true },
    // { key: 'ui-elements', label: 'UI Elements', isTitle: false, icon: 'package', link: '/ui-element' },
    // { key: 'widgets', label: 'Widgets', isTitle: false, icon: 'gift', link: '/widgets' },
    // {
    //     key: 'icons',
    //     label: 'Icons',
    //     isTitle: false,
    //     icon: 'cpu',
    //     collapsed: true,
    //     children: [
    //         { key: 'icon-unicons', label: 'Unicons', link: '/icons/unicon', parentKey: 'icons' },
    //         { key: 'icon-feather', label: 'Feather', link: '/icons/feather', parentKey: 'icons' },
    //         { key: 'icon-bootstrap', label: 'Bootstrap', link: '/icons/bootstrap', parentKey: 'icons' },
    //     ],
    // },
    // {
    //     key: 'forms',
    //     label: 'Forms',
    //     isTitle: false,
    //     icon: 'bookmark',
    //     collapsed: true,
    //     children: [
    //         { key: 'form-basic', label: 'Basic Elements', link: '/forms/basic', parentKey: 'forms' },
    //         { key: 'form-advanced', label: 'Advanced', link: '/forms/advanced', parentKey: 'forms' },
    //         { key: 'form-validation', label: 'Validation', link: '/forms/validation', parentKey: 'forms' },
    //         { key: 'form-wizard', label: 'Wizard', link: '/forms/wizard', parentKey: 'forms' },
    //         { key: 'form-editors', label: 'Editors', link: '/forms/editors', parentKey: 'forms' },
    //         { key: 'form-upload', label: 'File Uploads', link: '/forms/upload', parentKey: 'forms' }
    //     ],
    // },
    // { key: 'charts', label: 'Charts', isTitle: false, icon: 'bar-chart-2', link: '/charts' },
    // {
    //     key: 'tables',
    //     label: 'Tables',
    //     isTitle: false,
    //     icon: 'grid',
    //     collapsed: true,
    //     children: [
    //         { key: 'table-basic', label: 'Basic', link: '/tables/basic', parentKey: 'tables' },
    //         { key: 'table-advanced', label: 'Advanced Tables', link: '/tables/advanced', parentKey: 'tables' },
    //     ],
    // },
    // {
    //     key: 'maps',
    //     label: 'Maps',
    //     isTitle: false,
    //     icon: 'map',
    //     collapsed: true,
    //     children: [
    //         { key: 'maps-googlemaps', label: 'Google Maps', link: '/maps/googlemaps', parentKey: 'maps' },
    //         { key: 'maps-vectormaps', label: 'Vector Maps', link: '/maps/vectormaps', parentKey: 'maps' },
    //     ],
    // },
    // {
    //     key: 'menu-levels',
    //     label: 'Menu Levels',
    //     isTitle: false,
    //     icon: 'share-2',
    //     collapsed: true,
    //     children: [
    //         {
    //             key: 'menu-levels-1-1',
    //             label: 'Level 1.1',
    //             link: '/',
    //             parentKey: 'menu-levels',
    //             collapsed: true,
    //             children: [
    //                 {
    //                     key: 'menu-levels-2-1',
    //                     label: 'Level 2.1',
    //                     link: '/',
    //                     parentKey: 'menu-levels-1-1',
    //                     collapsed: true,
    //                     children: [
    //                         { key: 'menu-levels-3-1', label: 'Level 3.1', link: '/', parentKey: 'menu-levels-2-1' },
    //                         { key: 'menu-levels-3-2', label: 'Level 3.2', link: '/', parentKey: 'menu-levels-2-1' },
    //                     ],
    //                 },
    //                 { key: 'menu-levels-2-2', label: 'Level 2.2', link: '/', parentKey: 'menu-levels-1-1' },
    //             ],
    //         },
    //         { key: 'menu-levels-1-2', label: 'Level 1.2', link: '/', parentKey: 'menu-levels' },
    //     ],
    // },

];

// menu items for two column menu layout
const TWO_COl_MENU_ITEMS: MenuItem[] = [
    // {
    //     key: 'dashboard',
    //     icon: 'home',
    //     label: 'Dashboard',
    //     isTitle: true,
    //     children: [
    //         {
    //             key: 'ds-ecommerce',
    //             label: 'Ecommerce',
    //             link: '/dashboard/ecommerce',
    //             parentKey: 'dashboard',
    //         },
    //         {
    //             key: 'ds-analytics',
    //             label: 'Analytics',
    //             link: '/dashboard/analytics',
    //             parentKey: 'dashboard',
    //         }
    //     ],
    // },
    // {
    //     key: 'apps',
    //     icon: 'grid',
    //     label: 'Apps',
    //     isTitle: true,
    //     children: [
    //         {
    //             key: 'apps-calendar',
    //             label: 'Calendar',
    //             isTitle: false,
    //             icon: 'calendar',
    //             link: '/apps/calendar',
    //             parentKey: 'apps',
    //         },
    //         {
    //             key: 'apps-chat',
    //             label: 'Chat',
    //             isTitle: false,
    //             icon: 'message-square',
    //             link: '/apps/chat',
    //             parentKey: 'apps',
    //         },
    //         {
    //             key: 'apps-eglobe',
    //             label: 'Eglobe',
    //             isTitle: false,
    //             icon: 'globe',
    //             parentKey: 'apps',
    //             collapsed: true,
    //             children: [
    //                 {
    //                     key: 'eglobe-inbox',
    //                     label: 'Inbox',
    //                     link: '/apps/eglobe/inbox',
    //                     parentKey: 'apps-eglobe',
    //                 },
    //                 {
    //                     key: 'eglobe-read-eglobe',
    //                     label: 'Read Eglobe',
    //                     link: '/apps/eglobe/details',
    //                     parentKey: 'apps-eglobe',
    //                 },
    //                 {
    //                     key: 'eglobe-compose-eglobe',
    //                     label: 'Compose Eglobe',
    //                     link: '/apps/eglobe/compose',
    //                     parentKey: 'apps-eglobe',
    //                 },
    //             ],
    //         },
    //         {
    //             key: 'apps-projects',
    //             label: 'Projects',
    //             isTitle: false,
    //             icon: 'briefcase',
    //             parentKey: 'apps',
    //             collapsed: true,
    //             children: [
    //                 {key: 'project-list', label: 'List', link: '/apps/projects/list', parentKey: 'apps-projects'},
    //                 {
    //                     key: 'project-details',
    //                     label: 'Detail',
    //                     link: '/apps/projects/details',
    //                     parentKey: 'apps-projects',
    //                 }
    //             ],
    //         },
    //         {
    //             key: 'apps-tasks',
    //             label: 'Tasks',
    //             isTitle: false,
    //             icon: 'clipboard',
    //             parentKey: 'apps',
    //             collapsed: true,
    //             children: [
    //                 {key: 'task-list', label: 'List', link: '/apps/tasks/list', parentKey: 'apps-tasks'},
    //                 {key: 'task-kanban', label: 'Kanban Board', link: '/apps/tasks/kanban', parentKey: 'apps-tasks'},
    //             ],
    //         },
    //         {
    //             key: 'apps-file-manager',
    //             label: 'File Manager',
    //             isTitle: false,
    //             icon: 'folder-plus',
    //             link: '/apps/file-manager',
    //             parentKey: 'apps',
    //         },
    //     ],
    // },
    // {
    //     key: 'extra-pages',
    //     icon: 'file-text',
    //     label: 'Pages',
    //     isTitle: true,
    //     children: [
    //         {key: 'page-starter', label: 'Starter', link: '/pages/starter', parentKey: 'extra-pages'},
    //         {key: 'page-profile', label: 'Profile', link: '/pages/profile', parentKey: 'extra-pages'},
    //         {key: 'page-activity', label: 'Activity', link: '/pages/activity', parentKey: 'extra-pages'},
    //         {key: 'page-invoice', label: 'Invoice', link: '/pages/invoice', parentKey: 'extra-pages'},
    //         {key: 'page-pricing', label: 'Pricing', link: '/pages/pricing', parentKey: 'extra-pages'},
    //         {
    //             key: 'page-maintenance',
    //             label: 'Maintenance',
    //
    //             link: '/maintenance',
    //             parentKey: 'extra-pages',
    //         },
    //         {key: 'page-error-404', label: 'Error - 404', link: '/error-404', parentKey: 'extra-pages'},
    //         {key: 'page-error-500', label: 'Error - 500', link: '/error-500', parentKey: 'extra-pages'},
    //     ],
    // },
    // {
    //     key: 'components',
    //     icon: 'package',
    //     label: 'Components',
    //     isTitle: true,
    //     children: [
    //         {
    //             key: 'ui-elements',
    //             label: 'UI Elements',
    //             isTitle: false,
    //             icon: 'package',
    //             link: '/ui-element',
    //             parentKey: 'components'
    //         },
    //         {
    //             key: 'icons',
    //             label: 'Icons',
    //             isTitle: false,
    //             icon: 'cpu',
    //             parentKey: 'components',
    //             collapsed: true,
    //             children: [
    //                 {key: 'icon-unicons', label: 'Unicons', link: '/icons/unicon', parentKey: 'icons'},
    //                 {key: 'icon-feather', label: 'Feather', link: '/icons/feather', parentKey: 'icons'},
    //                 {key: 'icon-bootstrap', label: 'Bootstrap', link: '/icons/bootstrap', parentKey: 'icons'},
    //             ],
    //         },
    //         {
    //             key: 'charts',
    //             label: 'Charts',
    //             isTitle: false,
    //             icon: 'bar-chart-2',
    //             link: '/charts',
    //             parentKey: 'components'
    //         },
    //         {
    //             key: 'forms',
    //             label: 'Forms',
    //             isTitle: false,
    //             icon: 'bookmark',
    //             parentKey: 'components',
    //             collapsed: true,
    //             children: [
    //                 {key: 'form-basic', label: 'Basic Elements', link: '/forms/basic', parentKey: 'forms'},
    //                 {key: 'form-advanced', label: 'Advanced', link: '/forms/advanced', parentKey: 'forms'},
    //                 {key: 'form-validation', label: 'Validation', link: '/forms/validation', parentKey: 'forms'},
    //                 {key: 'form-wizard', label: 'Wizard', link: '/forms/wizard', parentKey: 'forms'},
    //                 {key: 'form-editors', label: 'Editors', link: '/forms/editors', parentKey: 'forms'},
    //                 {key: 'form-upload', label: 'File Uploads', link: '/forms/upload', parentKey: 'forms'}
    //             ],
    //         },
    //         {
    //             key: 'tables',
    //             label: 'Tables',
    //             isTitle: false,
    //             icon: 'grid',
    //             parentKey: 'components',
    //             collapsed: true,
    //             children: [
    //                 {key: 'table-basic', label: 'Basic', link: '/tables/basic', parentKey: 'tables'},
    //                 {key: 'table-advanced', label: 'Advanced Tables', link: '/tables/advanced', parentKey: 'tables'},
    //             ],
    //         },
    //         {
    //             key: 'maps',
    //             label: 'Maps',
    //             isTitle: false,
    //             icon: 'map',
    //             parentKey: 'components',
    //             collapsed: true,
    //             children: [
    //                 {key: 'maps-googlemaps', label: 'Google Maps', link: '/maps/googlemaps', parentKey: 'maps'},
    //                 {key: 'maps-vectormaps', label: 'Vector Maps', link: '/maps/vectormaps', parentKey: 'maps'},
    //             ],
    //         },
    //         {
    //             key: 'menu-levels',
    //             label: 'Menu Levels',
    //             isTitle: false,
    //             icon: 'share-2',
    //             parentKey: 'components',
    //             collapsed: true,
    //             children: [
    //                 {
    //                     key: 'menu-levels-1-1',
    //                     label: 'Level 1.1',
    //                     link: '/',
    //                     parentKey: 'menu-levels',
    //                     collapsed: true,
    //                     children: [
    //                         {
    //                             key: 'menu-levels-2-1',
    //                             label: 'Level 2.1',
    //                             link: '/',
    //                             parentKey: 'menu-levels-1-1',
    //                             collapsed: true,
    //                             children: [
    //                                 {
    //                                     key: 'menu-levels-3-1',
    //                                     label: 'Level 3.1',
    //                                     link: '/',
    //                                     parentKey: 'menu-levels-2-1',
    //                                 },
    //                                 {
    //                                     key: 'menu-levels-3-2',
    //                                     label: 'Level 3.2',
    //                                     link: '/',
    //                                     parentKey: 'menu-levels-2-1',
    //                                 },
    //                             ],
    //                         },
    //                         {key: 'menu-levels-2-2', label: 'Level 2.2', link: '/', parentKey: 'menu-levels-1-1'},
    //                     ],
    //                 },
    //                 {key: 'menu-levels-1-2', label: 'Level 1.2', link: '/', parentKey: 'menu-levels'},
    //             ],
    //         },
    //     ],
    // },
    // {key: 'widgets', label: 'Widgets', isTitle: false, icon: 'gift', link: '/widgets'},
];

// menu items for horizontal layout
const HORIZONTAL_MENU_ITEMS: MenuItem[] = [
    {
        key: 'dashboard',
        icon: 'home',
        label: 'Dashboards',
        isTitle: true,
        collapsed: true,
        children: [
            {
                key: 'ds-ecommerce',
                label: 'Ecommerce',
                link: '/dashboard/ecommerce',
                parentKey: 'dashboard',
            },
            {
                key: 'ds-analytics',
                label: 'Analytics',
                link: '/dashboard/analytics',
                parentKey: 'dashboard',
            }
        ],
    },
    {
        key: 'apps',
        icon: 'layers',
        label: 'Apps',
        isTitle: true,
        collapsed: true,
        children: [
            {
                key: 'apps-calendar',
                label: 'Calendar',
                isTitle: false,
                icon: 'calendar',
                link: '/apps/calendar',
                parentKey: 'apps',
            },
            {
                key: 'apps-chat',
                label: 'Chat',
                isTitle: false,
                icon: 'message-square',
                link: '/apps/chat',
                parentKey: 'apps',
            },
            {
                key: 'apps-eglobe',
                label: 'Eglobe',
                isTitle: false,
                icon: 'globe',
                parentKey: 'apps',
                collapsed: true,
                children: [
                    {
                        key: 'eglobe-inbox',
                        label: 'Inbox',
                        link: '/apps/eglobe/inbox',
                        parentKey: 'apps-eglobe',
                    },
                    {
                        key: 'eglobe-read-eglobe',
                        label: 'Read Eglobe',
                        link: '/apps/eglobe/details',
                        parentKey: 'apps-eglobe',
                    },
                    {
                        key: 'eglobe-compose-eglobe',
                        label: 'Compose Eglobe',
                        link: '/apps/eglobe/compose',
                        parentKey: 'apps-eglobe',
                    },
                ],
            },
            {
                key: 'apps-projects',
                label: 'Projects',
                isTitle: false,
                icon: 'briefcase',
                parentKey: 'apps',
                collapsed: true,
                children: [
                    {key: 'project-list', label: 'List', link: '/apps/projects/list', parentKey: 'apps-projects'},
                    {
                        key: 'project-details',
                        label: 'Detail',
                        link: '/apps/projects/details',
                        parentKey: 'apps-projects',
                    },
                ],
            },
            {
                key: 'apps-tasks',
                label: 'Tasks',
                isTitle: false,
                icon: 'clipboard',
                parentKey: 'apps',
                collapsed: true,
                children: [
                    {key: 'task-list', label: 'List', link: '/apps/tasks/list', parentKey: 'apps-tasks'},
                    {key: 'task-kanban', label: 'Kanban Board', link: '/apps/tasks/kanban', parentKey: 'apps-tasks'},
                ],
            },
            {
                key: 'apps-file-manager',
                label: 'File Manager',
                isTitle: false,
                icon: 'folder-plus',
                link: '/apps/file-manager',
                parentKey: 'apps',
            },
        ],
    },
    {
        key: 'components',
        icon: 'briefcase',
        label: 'Components',
        isTitle: true,
        collapsed: true,
        children: [
            {
                key: 'ui-elements',
                label: 'UI Elements',
                isTitle: false,
                icon: 'package',
                link: '/ui-element',
                parentKey: 'components'
            },
            {key: 'widgets', label: 'Widgets', isTitle: false, icon: 'gift', link: '/widgets', parentKey: 'components'},

            {
                key: 'forms',
                label: 'Forms',
                isTitle: false,
                icon: 'bookmark',
                parentKey: 'components',
                collapsed: true,
                children: [
                    {key: 'form-basic', label: 'Basic Elements', link: '/forms/basic', parentKey: 'forms'},
                    {key: 'form-advanced', label: 'Advanced', link: '/forms/advanced', parentKey: 'forms'},
                    {key: 'form-validation', label: 'Validation', link: '/forms/validation', parentKey: 'forms'},
                    {key: 'form-wizard', label: 'Wizard', link: '/forms/wizard', parentKey: 'forms'},
                    {key: 'form-editors', label: 'Editors', link: '/forms/editors', parentKey: 'forms'},
                    {key: 'form-upload', label: 'File Uploads', link: '/forms/upload', parentKey: 'forms'}
                ],
            },
            {
                key: 'charts',
                label: 'Charts',
                isTitle: false,
                icon: 'bar-chart-2',
                link: '/charts',
                parentKey: 'components'
            },
            {
                key: 'tables',
                label: 'Tables',
                isTitle: false,
                icon: 'grid',
                parentKey: 'components',
                collapsed: true,
                children: [
                    {key: 'table-basic', label: 'Basic', link: '/tables/basic', parentKey: 'tables'},
                    {key: 'table-advanced', label: 'Advanced Tables', link: '/tables/advanced', parentKey: 'tables'},
                ],
            },
            {
                key: 'icons',
                label: 'Icons',
                isTitle: false,
                icon: 'cpu',
                parentKey: 'components',
                collapsed: true,
                children: [
                    {key: 'icon-unicons', label: 'Unicons', link: '/icons/unicon', parentKey: 'icons'},
                    {key: 'icon-feather', label: 'Feather', link: '/icons/feather', parentKey: 'icons'},
                    {key: 'icon-bootstrap', label: 'Bootstrap', link: '/icons/bootstrap', parentKey: 'icons'},
                ],
            },
            {
                key: 'maps',
                label: 'Maps',
                isTitle: false,
                icon: 'map',
                parentKey: 'components',
                collapsed: true,
                children: [
                    {key: 'maps-googlemaps', label: 'Google Maps', link: '/maps/googlemaps', parentKey: 'maps'},
                    {key: 'maps-vectormaps', label: 'Vector Maps', link: '/maps/vectormaps', parentKey: 'maps'},
                ],
            },
        ],
    },
    {
        key: 'extra-pages',
        label: 'Pages',
        isTitle: false,
        icon: 'file-text',
        collapsed: true,
        children: [
            {key: 'page-starter', label: 'Starter', isTitle: false, link: '/pages/starter', parentKey: 'extra-pages'},
            {key: 'page-profile', label: 'Profile', isTitle: false, link: '/pages/profile', parentKey: 'extra-pages'},
            {
                key: 'page-activity',
                label: 'Activity',
                isTitle: false,
                link: '/pages/activity',
                parentKey: 'extra-pages'
            },
            {key: 'page-invoice', label: 'Invoice', isTitle: false, link: '/pages/invoice', parentKey: 'extra-pages'},
            {key: 'page-pricing', label: 'Pricing', isTitle: false, link: '/pages/pricing', parentKey: 'extra-pages'},
            {
                key: 'page-maintenance',
                label: 'Maintenance',
                isTitle: false,
                link: '/maintenance',
                parentKey: 'extra-pages',
            },
            {key: 'page-error-404', label: 'Error - 404', isTitle: false, link: '/error-404', parentKey: 'extra-pages'},
            {key: 'page-error-500', label: 'Error - 500', isTitle: false, link: '/error-500', parentKey: 'extra-pages'},
        ],
    }

];

export {MENU_ITEMS, TWO_COl_MENU_ITEMS, HORIZONTAL_MENU_ITEMS};
